#!/bin/bash
set -fueo pipefail

if [[ $(id -u) -ne 0 ]] ; then echo "Please run as root" ; exit 1 ; fi
#disable interactive mode 
#so some confirmation won't bug you
export DEBIAN_FRONTEND=noninteractive
#need sudo access
#backing up old files
mkdir -p bak
ls ~/.bashrc && mv ~/.bashrc $PWD/bak/bashrc
ls ~/.vimrc && mv ~/.vimrc $PWD/bak/vimrc
ls ~/.tmux.conf && mv ~/.tmux.conf $PWD/bak/tmux.conf
ls ~/.screenrc && mv ~/.screenrc $PWD/bak/.screenrc
mkdir -p ~/.vim/
ln -snf $PWD/bashrc ~/.bashrc
ln -snf $PWD/bash_aliases ~/.bash_aliases
ln -snf $PWD/bash_home_brew_script ~/.bash_home_brew_script
ln -snf $PWD/vimrc ~/.vimrc
ln -snf $PWD/tmux.conf ~/.tmux.conf
ln -snf $PWD/screenrc ~/.screenrc
ln -snf $PWD/vim_colors ~/.vim/colors
ln -snf $PWD/notes ~/notes
ln -snf $PWD/tmux_lunch ~/.tmux_lunch
chmod +x ~/.tmux_lunch
mv ~/notes $PWD/bak/notes
#clone git repo frequently used
git clone https://github.com/ceacar/utility.git $PWD/utility
git clone https://github.com/ceacar/albert_practice.git $PWD/albert_practice

#some essential dev env
apt-get -y install build-essential cmake
apt-get -y install python-dev python3-dev python-pip
apt-get -y install python-dev libxml2-dev libxslt-dev
#you complete me prerequisite
apt-get -y install libncurses5-dev libgnome2-dev libgnomeui-dev \
    libgtk2.0-dev libatk1.0-dev libbonoboui2-dev \
    libcairo2-dev libx11-dev libxpm-dev libxt-dev python-dev \
    python3-dev ruby-dev lua5.1 lua5.1-dev libperl-dev git
pip install --upgrade virtualenv
pip install --upgrade pip 

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
#change permission of the directory so vim could install everything when other user need it
chmod -R 755 ~/.vim
#go into vim and type :PluginInstall
#after than run following
#cd ~/.vim/bundle/YouCompleteMe
#./install.py --clang-completer




#git alias
git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.ci commit
git config --global alias.st status
git config --global alias.df diff
git config --global alias.pr 'pull --rebase'

#git 
git config --global user.email "alex.yonder@yahoo.com"
git config --global user.name "ceacar"

cd ~/projects/
git clone https://github.com/vim/vim.git
./configure --with-features=huge --enable-multibyte --enable-rubyinterp=yes --enable-pythoninterp=yes --with-python-config-dir=/usr/lib/python2.7/config --enable-python3interp=yes --with-python3-config-dir=/usr/lib/python3.5/config --enable-perlinterp=yes --enable-luainterp=yes --enable-gui=gtk2 --enable-cscope --prefix=/usr
make install


#install for vim
vim -c 'PluginInstall' -c 'qa!'

#compile you completeme
cd ~/.vim/bundle/YouCompleteMe
./install.py --clang-completer



