#!/bin/bash

# enable color support of ls and also add handy aliases
if $is_linux;then
  if [ -x /usr/bin/dircolors ]; then
      test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
      alias ls='ls --color=auto'
      #alias dir='dir --color=auto'
      #alias vdir='vdir --color=auto'

  fi
fi

if $is_mac;then
  alias ls='ls -GFh'
fi

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lsize='ls -Salr'
alias less='less -R'
alias sl='ls'
alias scratch_notes='vim /tmp/temp_scratch.txt'
alias longestlines="awk 'length > max_length { max_length = length; longest_line = \$0;print max_length,\$0}'"
alias secondsSinceMidNightToTime='python ~/Documents/code/secondsSinceMidNightToTime.py'
alias reverseSecondsSinceMidNightToTime='python ~/Documents/code/reverseSecondsSinceMidNightToTime.py'
alias stockEndTime="echo 57600000000"
alias stockStartTime="echo 34200000000"
alias lstime="ls -ltr"
alias phistory="cat ~/.persistent_history"
alias lssize="du -sh *"
alias lscolor="ls --color"
alias lsdir="ls -d */"
alias refreshbashrc='source ~/.bashrc'
alias dockerkillall='docker kill $(docker ps -q)'
alias vimnoplugin='vim -u NONE'
alias vimwithoutycm="vim --cmd 'set rtp^='~/.vimrd''"
alias uname_output="$(uname -s)"
alias ide="vim -u ~/.vimrc_ide"
#alias vim="/usr/local/bin/vim"
#alias pypy="/opt/share/pypy/current/pypy-5.0-linux_x86_64-portable/bin/pypy"
