let g:go_version_warning = 0
nnoremap cc i<space><esc>
"noremap <Up> <NOP>
"noremap <Down> <NOP>
"noremap <Left> <NOP>
"noremap <Right> <NOP>

"noremap k j
"noremap j k

"syntax on
"highlight Comment ctermfg=darkgreen
"highlight BadWhitespace ctermbg=red guibg=darkred
"highlight highlight_id_cursor=darkgreen
" size of a hard tabstop
"set tabstop=4
"
"disable annoying visual flashing
"set novisualbell
set visualbell
set t_vb=

" size of an "indent"
set shiftwidth=2

" a combination of spaces and tabs are used to simulate tab stops at a width
" other than the (hard)tabstop
set softtabstop=2

" make "tab" insert indents instead of tabs at the beginning of a line
set smarttab
" if you search with 'Mykeyword', it will search with case sensitive, if with
" " 'mykeyword', it will search with case insensitive
set smartcase

"another color scheme
"Plugin 'jnurmine/Zenburn'
"Plugin 'altercation/vim-colors-solarized'


" always uses spaces instead of tab characters
"set expandtab


" better set to utf 8 while working with python
" set encoding=utf-8
" above command triiger error e518 on vim so disabled


"vundle setup
set nocompatible              " required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Plugin 'derekwyatt/vim-scala'
" this plugin seems doesn't do anything
" Plugin 'derekwyatt/vim-scala'

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" vim-go ide
Plugin 'fatih/vim-go'

" Add all your plugins here (note older versions of Vundle used Bundle instead of Plugin)

" navigate any char on the screen
Plugin 'easymotion/vim-easymotion'

" enable python indentation plugin
Plugin 'vim-scripts/indentpython.vim'

" ctrl + p will search on all files in current directory
Plugin 'kien/ctrlp.vim'

" nerd tree the gui acting as a file browser in vim
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'

" ner tree with tab, use tab to invoke nerd tree
"Plugin 'jistr/vim-nerdtree-tabs'

" PEP8 code check
Plugin 'nvie/vim-flake8'
"Syntastic a syntax check tool
Plugin 'vim-syntastic/syntastic'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" Required for YouCompleteMe
set encoding=utf-8

" Enable folding
set foldmethod=indent
set foldlevel=99
" hi Folded guibg=#A0A0A0
hi Folded ctermbg=242
" Enable folding with the spacebar
nnoremap <space> za

" F2 to toggle the paste and inv paste
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode

" F3 to toggle relative line number on and off
function! NumberToggle()
  "echo &relativenumber
  "echo &number
  if(&relativenumber == 1)
    set number
  else
    set relativenumber
  endif
endfunc



nnoremap <F3> :call NumberToggle()<cr>

" disabled this, since this will cause termux vim to toggle number line after
" :w
" set invnumber nornu

"nnoremap <F11> :edit!<cr>
nnoremap <F5> :set invnumber nornu<cr>
" toggle ignore case
nnoremap <F6> :set ic!<cr>
nmap <F1> :set ignorecase! ignorecase?

"Remove all trailing whitespace by pressing F5
"either one below will work
nnoremap <F4> :%s/ $//g<cr>
"nnoremap <F8> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar><CR>

" enable vim auto reload vimrc config
" augroup myvimrchooks
"     au!
"     autocmd bufwritepost .vimrc source ~/.vimrc
" augroup END

" enable vim auto reload vimrc config, more cross platform friendly
augroup myvimrc
    au!
    au BufWritePost .vimrc,_vimrc,vimrc,.gvimrc,_gvimrc,gvimrc so $MYVIMRC | if has('gui_running') | so $MYGVIMRC | endif
augroup END

" enable the folding plugin
"Plugin 'tmhedberg/SimpylFold'


" enable python indentation
au BufNewFile,BufRead *.py
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=200 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix |

au BufNewFile,BufRead *.js,*.html,*.css,*.yml
    \ set tabstop=2 |
    \ set softtabstop=2 |
    \ set shiftwidth=2 |

au BufNewFile,BufRead *.scala,*.java
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
au BufNewFile,BufRead *.go
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=200 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix |


"au BufNewFile,BufRead *.c,*.cpp
"    \ set cindent |
"    \ set shiftwidth=2 |
"    \ set expandtab |

" flag excess space
au BufRead,BufNewFile *.py,*.pyw,*.c,*.h
  \ match BadWhitespace /\s\+$/
" vim auto completion
Plugin 'Valloric/YouCompleteMe'
let g:ycm_autoclose_preview_window_after_completion=1
map <leader>g  :YcmCompleter GoToDefinitionElseDeclaration<CR>
"<leader> is a the primary key: if it's space it will be 'space-g' will go into definition

"let g:NERDTreeShowIgnoredStatus = 1
"code highlight
" disabled for conflict with you complete me   :w will pop out a whitebar on
" left side
" Plugin 'scrooloose/syntastic'

" python code pretty
let python_highlight_all=1

"hide pyc from nerd tree
let NERDTreeIgnore=['\.pyc$', '\~$'] "ignore files in NERDTree


"let nerd tree start itself
" autocmd VimEnter * NERDTree | wincmd p
"map <Leader>n <plug>NERDTreeTabsToggle<CR>
nmap <F8> :NERDTreeToggle<CR>
" remap pep8 check to F8
"autocmd FileType python map <buffer> <F8> :call flake8#Flake8()<CR>

" make backspaces more powerfull
set backspace=indent,eol,start

syntax on
colorscheme xedit
highlight Comment ctermfg=darkgreen

"highlight Comment guifg=darkgreen
highlight BadWhitespace ctermbg=red guibg=darkred


vnoremap <silent> # :s#^#\##<cr>:noh<cr>
vnoremap <silent> -# :s#^\###<cr>:noh<cr>

" fast navigation to char

nmap s <Plug>(easymotion-s2)
nmap t <Plug>(easymotion-t2)

" prevents from wrapping long code
"set formatoptions-=t


"set ycm extra conf
let g:ycm_global_ycm_extra_conf = '~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'
" let nerd tree tab open up on vim startup
"let g:nerdtree_tabs_open_on_console_startup=1
"syntastic settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_python_pylint_post_args="--max-line-length=120"

" see :h syntastic-loclist-callback
function! SyntasticCheckHook(errors)
  if !empty(a:errors)
      let g:syntastic_loc_list_height = min([len(a:errors), 10])
  endif
endfunction

" searching for tags
nnoremap <C-m> :CtrlPTag<CR>

":tabnew :tag  funcname
nnoremap <C-n> <C-w><C-]><C-w>T
